### ISSUE TITLE
[AWS] Add restrictive endpoint policies for STS, S3, and Kinesis?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#10]
https://github.com/databricks/terraform-databricks-sra/blob/8f1cf46c5a3afa3e525b02d092a8f40d7ea74cbc/aws/tf/modules/sra/privatelink.tf#L2

Currently all these endpoints will have a default policy, however, we could scale it back to include explicit allows to Databricks buckets and data buckets for example. However, it could add more overhead to manage in the long run

**Comment by jdbraun-db** [comment]
Fixed in this PR: https://github.com/databricks/terraform-databricks-sra/pull/35
