### ISSUE TITLE
[AWS] Investigate implementing DNS Firewall for additional gap coverage on AWS Network Firewall

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#106]
- https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-dns-firewall.html

> DNS Firewall and Network Firewall both offer domain name filtering, but for different types of traffic. With DNS Firewall and Network Firewall together, you can configure domain-based filtering for application layer traffic over two different network paths.

> DNS Firewall provides filtering for outbound DNS queries that pass through the Route 53 Resolver from applications within your VPCs. You can also configure DNS Firewall to send custom responses for queries to blocked domain names.

> Network Firewall provides filtering for both network and application layer traffic, but does not have visibility into queries made by Route 53 Resolver.

**Comment by jdbraun-db** [comment]
updated with #112
