### ISSUE TITLE
[AWS] System table bucket needs to be added to restrictive S3 endpoint policy

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#109]
- https://docs.databricks.com/en/resources/ip-domain-region.html#s3-addresses
- https://github.com/databricks/terraform-databricks-sra/blob/1fdd92178b943d465a91cd8801ffb238cfff3c70/aws/tf/modules/sra/privatelink.tf#L52

**Comment by jdbraun-db** [comment]
updated with #112
