### ISSUE TITLE
[AWS] Missing admin configurations?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#11]
https://github.com/databricks/terraform-databricks-sra/blob/8f1cf46c5a3afa3e525b02d092a8f40d7ea74cbc/aws/tf/modules/sra/databricks/admin_configuration/admin_configuration.tf#L3C1-L16C2

This list is missing a few admin configurations and should be reviewed + compared to existing best practices from the trust center

**Comment by jdbraun-db** [comment]
Closing until the admin configs are released by provider
