### ISSUE TITLE
SRA authentication needs to be fixed

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#12]
https://github.com/databricks/terraform-databricks-sra/blob/8f1cf46c5a3afa3e525b02d092a8f40d7ea74cbc/aws/tf/modules/sra/databricks.tf#L118C1-L123C8

SRA authentication needs to be updated with OAuth, similar to the rest of the repo

**Comment by jdbraun-db** [comment]
resolved
