### ISSUE TITLE
service principal on wrong provider?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#19]
https://github.com/databricks/terraform-databricks-sra/blob/c1e247be2264f0135cda36c2aaec85ede8de8572/aws/tf/modules/sra/databricks_workspace.tf#L34C1-L43C2

This should be at the account level provider, not the workspace level provider - it's causing these SPs to be created, assigned, but not deleted

**Comment by jdbraun-db** [comment]
resolved
