### ISSUE TITLE
Why aren't we using booleans?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#20]
https://github.com/databricks/terraform-databricks-sra/blob/c1e247be2264f0135cda36c2aaec85ede8de8572/aws/tf/modules/sra/databricks_workspace.tf#L69C1-L114C4

These shouldn't be hard commented out, should be at the top module level if they decide to turn on / off

**Comment by jdbraun-db** [comment]
resolved
