### ISSUE TITLE
[AWS] Remove root metastore and add workspace level catalogs

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#30]
In version 1.30 of the Terraform provider, you can make the root metastore optional. We should do that to isolate catalogs to the workspace with their own storage credential, then if so choose, share them to other workspaces as the admin

**Comment by jdbraun-db** [comment]
This is currently blocked by 1.30 authentication issues, the release that this (no-root metastore) was introduced

**Comment by jdbraun-db** [comment]
Resolved with: https://github.com/databricks/terraform-databricks-sra/pull/41
