### ISSUE TITLE
[AWS] Add a no internet connectivity option

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#31]
Given we control creating public subnets and other networking objects here: https://github.com/databricks/terraform-databricks-sra/blob/main/aws/tf/modules/sra/data_plane_hardening/firewall/firewall.tf

we can do a no internet connectivity option as well

**Comment by jdbraun-db** [comment]
Added as an operation mode in this PR: https://github.com/databricks/terraform-databricks-sra/pull/35
