### ISSUE TITLE
[AWS] Remove legacy instance profile reference in role ARN

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#36]
https://github.com/databricks/terraform-databricks-sra/blob/45e5e50a81f2741b5407d37c6a74654db63472bc/aws/tf/modules/sra/credential.tf#L220

With UC this is no longer needed and can be removed

**Comment by jdbraun-db** [comment]
Closed with PR: https://github.com/databricks/terraform-databricks-sra/pull/41
