### ISSUE TITLE
[AWS] Custom configuration for workspace is incorrect

### ISSUE THREAD

**Issue by sastafford** [databricks/terraform-databricks-sra#46]
Environment: AWS

I'm running `terraform apply -var-file template.tfvars` into a brand new AWS account with no other resources loaded.  I had to comment out all the custom_config variables from the file to get it work.  

Linked to this issue in the Databricks Terraform plugin: https://github.com/databricks/terraform-provider-databricks/issues/3365

`https://github.com/databricks/terraform-databricks-sra/blob/main/aws/tf/modules/sra/databricks_workspace/workspace_security_modules/admin_configuration/admin_configuration.tf`

**Comment by JDBraun** [comment]
Thanks @sastafford for the issue! Which Databricks provider version were you using?

**Comment by JDBraun** [comment]
@sastafford - I'm failing to recreate it, can you provide some additional information:
- Did you add any additional configurations to the list?
- What tier of the product are you on (premium / enterprise)?

**Comment by grzybniak** [comment]
Thx @sastafford for the fix. It helped a lot. I am using PREMIUM plan

**Comment by jdbraun-db** [comment]
Resolved with: https://github.com/databricks/terraform-databricks-sra/pull/50
