### ISSUE TITLE
[AWS] 8443-8451 need to be added for PrivateLink SGs

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#51]
https://github.com/databricks/terraform-databricks-sra/blob/4c38239133d39fd88cd080961221c08fa3173f43/aws/tf/modules/sra/privatelink.tf#L245

**Comment by jdbraun-db** [comment]
Specifically on the REST endpoint for PL

**Comment by jdbraun-db** [comment]
addressed here: https://github.com/databricks/terraform-databricks-sra/blob/6523d99b0eb10e091509745bc34aa8d34e5976f9/aws/tf/modules/sra/privatelink.tf#L23
