### ISSUE TITLE
[AWS] Update "Standard" to "Sandbox" as a deployment method

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#52]
In a best practice world, unrestricted outbound access is not always a best practice. However, having this access is great for sandbox environments to test out with development data, new APIs, etc.

So proposing that this is changed to Sandbox to better reflect it's status

**Comment by jdbraun-db** [comment]
addressed here: https://github.com/databricks/terraform-databricks-sra/blob/main/aws/tf/README.md#operation-mode
