### ISSUE TITLE
[AWS] FIX #50 broke Example Cluster creation

### ISSUE THREAD

**Issue by alexandre-sumer** [databricks/terraform-databricks-sra#53]
https://github.com/databricks/terraform-databricks-sra/pull/50/files

This PR removed some parameters and added `"enforceUserIsolation"          = "true"`.
This setting does not enable creating the Example Cluster when setting the following to true.

`enable_cluster_boolean           = true // WARNING: Clusters will spin-up Databricks clusters and AWS EC2 instances`

Setting `"enforceUserIsolation"          = "false"` enables to create the Cluster.

**Comment by JDBraun** [comment]
You can find a working example in the recent PR here: https://github.com/databricks/terraform-databricks-sra/pull/57

Will try to get this merged by next week at the latest

**Comment by jdbraun-db** [comment]
addressed here by specifying the data security mode: https://github.com/databricks/terraform-databricks-sra/blob/6523d99b0eb10e091509745bc34aa8d34e5976f9/aws/tf/modules/sra/databricks_workspace/workspace_security_modules/cluster_configuration/cluster_configuration.tf#L35
