### ISSUE TITLE
[AWS] Add Govcloud ARN support

### ISSUE THREAD

**Issue by metrocavich** [databricks/terraform-databricks-sra#54]
Many of the ARN need to be modified not only to allow for different role/bucket/resource names but the second identifier in an ARN
"arn:aws:iam::414351767826:user/databricks-datasets-readonly-user" needs to become something like "arn:aws-us-gov:iam::414351767826:user/databricks-datasets-readonly-user"

We also need to include the appropriate UC roles for Govcloud.

**Comment by jdbraun-db** [comment]
New top-level folder for AWS gov cloud will be added

**Comment by jdbraun-db** [comment]
closed with: https://github.com/databricks/terraform-databricks-sra/pull/77
