### ISSUE TITLE
[AWS] AWS VPC Endpoints - Wrong Security Group

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#55]
AWS VPC endpoints are using the workspace security group instead of the privatelink security group 

https://github.com/databricks/terraform-databricks-sra/blob/254468075f84efe927bf48fe6cd8e4523cfc94a5/aws/tf/modules/sra/privatelink.tf#L208

**Comment by jdbraun-db** [comment]
addressed here: https://github.com/databricks/terraform-databricks-sra/pull/57

PL has been updated: https://github.com/databricks/terraform-databricks-sra/blob/6523d99b0eb10e091509745bc34aa8d34e5976f9/aws/tf/modules/sra/privatelink.tf#L255
