### ISSUE TITLE
[AWS] Remove Egress SG Rules for PrivateLink Endpoints

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#56]
Egress rules are not needed for PrivateLink endpoints since it's only inbound from the cluster itself 

https://github.com/databricks/terraform-databricks-sra/blob/254468075f84efe927bf48fe6cd8e4523cfc94a5/aws/tf/modules/sra/privatelink.tf#L274

**Comment by jdbraun-db** [comment]
addressed here: https://github.com/databricks/terraform-databricks-sra/pull/57.

egress rules removed: https://github.com/databricks/terraform-databricks-sra/blob/6523d99b0eb10e091509745bc34aa8d34e5976f9/aws/tf/modules/sra/privatelink.tf#L2
