### ISSUE TITLE
[AWS] Missing docs link for hive metastores

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#62]
https://github.com/databricks/terraform-databricks-sra/blob/6523d99b0eb10e091509745bc34aa8d34e5976f9/aws/tf/sra.tf#L66

This needs the doc link to the hive metastores

**Comment by jdbraun-db** [comment]
Closed with: https://github.com/databricks/terraform-databricks-sra/pull/66
