### ISSUE TITLE
[AWS] Disable root bucket and logging versioning

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#64]
Disable root bucket and audit log versioning to put it in line with the documentation from the provider: https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/aws-workspace#root-bucket

**Comment by JDBraun** [comment]
This has specific implications to CloudFetch: https://docs.databricks.com/en/integrations/odbc/capability.html#arrow-serialization-in-odbc

**Comment by JDBraun** [comment]
Same documentation tells how to set life cycle policy if bucket versioning is already enabled

**Comment by jdbraun-db** [comment]
Closed with: https://github.com/databricks/terraform-databricks-sra/pull/66
