### ISSUE TITLE
Optional Firewall Configuration?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#7]
https://github.com/databricks/terraform-databricks-sra/blob/8f1cf46c5a3afa3e525b02d092a8f40d7ea74cbc/aws/tf/sra.tf#L38

While folks may have existing firewall configurations that they use, especially in a hub & spoke environment, should we include a boolean to include an AWS firewall with additional subnets?

**Comment by jdbraun-db** [comment]
Added in recent PR for AWS
