### ISSUE TITLE
[AWS] Implement Unity Catalog Assume Role Data Source

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#70]
1.47 introduced a data source for the assume role for Unity Catalog, this can be used instead of writing it out to simplify the code: https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.47.0

**Comment by jdbraun-db** [comment]
closed with #71

**Comment by jdbraun-db** [comment]
closed with https://github.com/databricks/terraform-databricks-sra/pull/84
