### ISSUE TITLE
[AWS] Usage of databricks-datasets-readonly-user caused InvalidPolicyDocument

### ISSUE THREAD

**Issue by hwang-db** [databricks/terraform-databricks-sra#82]
Reference to this iam user caused InvalidPolicyDocument:
"arn:aws:iam::414351767826:user/databricks-datasets-readonly-user"

Link to this usage in SRA repo: https://github.com/databricks/terraform-databricks-sra/blob/4a980bd767bd5398e891c9f2948320a61c9d98d7/aws/tf/modules/sra/privatelink.tf#L220C9-L220C76

**Comment by jdbraun-db** [comment]
I'll address this in the new PR, with the move to UC, I'm assuming this won't be needed, but will verify

**Comment by JDBraun** [comment]
@hwang-db the user arn has changed to: **arn:aws:iam::414351767826:user/databricks-datasets-readonly-user-prod**, which explains the invalid arn in the policy. see below screenshot when accessing the _samples_ db.
![Screenshot 2024-08-26 at 12 32 38 PM](https://github.com/user-attachments/assets/67fe7993-2ff6-4383-9df1-8f85c4088b7e)

theoretically if the samples dataset isn't used, then this may not be required, but testing always recommend. 

I'm updating the ARN in the new PR and adding a note that restrictive endpoints are subject to change.

**Comment by jdbraun-db** [comment]
closed with https://github.com/databricks/terraform-databricks-sra/pull/84
