### ISSUE TITLE
[AWS] Remove or update redundant variables in sra.tf for AWS and AWS Gov?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#85]
I think we can remove the following variables, thoughts @airizarryDB and @metrocavich?

- **sg_ingress_protocol** and **sg_egress_protocol**: These are only used for the internode communication rules, which is a requirement regardless.
- **relay_vpce_service**, **workspace_vpce_service**, and **hive_metastore_fqdn**: We now assume all three of these from a data source, so not really needed if we have the region, so doesn't need to be in the main entry point. So, these can be moved to local variables.
- **firewall_protocol_deny_list**: This actually isn't used anymore, so does need to go

**Comment by airizarryDB** [comment]
Closed with #84
