### ISSUE TITLE
[AWS] Only create admin SP if SAT is being used

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#89]
Can remove the admin SP from normal workflows, since it isn't complex code to add-on. In addition, since an SP is now enforced for TF, and not basic auth, the user would know how to do so manually in a worst case scenario

**Comment by jdbraun-db** [comment]
updated with #94 
- we use the same SP that does the account admin for the entire repo, no additional SP is created. https://github.com/databricks/terraform-databricks-sra/blob/7bfbcd8455d807eb2cdff220ad89b8bdd93d0d97/aws/tf/modules/sra/databricks_workspace.tf#L90
