### ISSUE TITLE
Add boolean to disable metastore creation?

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#9]
https://github.com/databricks/terraform-databricks-sra/blob/8f1cf46c5a3afa3e525b02d092a8f40d7ea74cbc/aws/tf/modules/sra/databricks/unity_catalog/unity_catalog.tf#L4C1-L8C2

If this module is ran multiple times in the same region, then it will fail out. This should be parameterized where if the metastore is already created, an ID can be passed in to attach it

**Comment by jdbraun-db** [comment]
Added in recent PR for AWS
