### ISSUE TITLE
[AWS] Remove explicit depends on workspace for certain resources and modules

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#91]
The explicit depends on for the workspace module can cause security group, user, and metastore assignment to threaten to recreate if workspace is patched, even if it's update safe variables like network, custom tags, etc or not related

SG for PL example:
- https://github.com/databricks/terraform-databricks-sra/blob/ed5455814b4ecc9ce43aa27a5bc159695127e6a2/aws/tf/modules/sra/privatelink.tf#L291

Will need to debug where depends on is truly required and where's its not

**Comment by jdbraun-db** [comment]
updated with #94 
- privatelink no longer dependent on workspace, however, uc assignment needs to stay to prevent issues on deployment
