### ISSUE TITLE
[AWS] SAT update based on new release

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#93]
SAT updated their deployment, causing a breaking change in SRA. It will need to be fixed.
- https://github.com/databricks-industry-solutions/security-analysis-tool/commit/c9da49f249dd9830dc5ded33a1b4ca94b1b02537

**Comment by jdbraun-db** [comment]
closed with #94 
- https://github.com/databricks/terraform-databricks-sra/blob/7bfbcd8455d807eb2cdff220ad89b8bdd93d0d97/aws/tf/modules/sra/databricks_workspace.tf#L79
