### ISSUE TITLE
[AWS] Installing system tables requires databricks provider 1.51

### ISSUE THREAD

**Issue by sastafford** [databricks/terraform-databricks-sra#97]
Cloud: AWS
By default the provider is set to 1.50.  Have to manually upgrade provider.tf to 1.51 to resolve.

**Comment by JDBraun** [comment]
@sastafford what resource are you using? it works fine with 1.50.0 on me - it looks like the system schema was added in 1.28: https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.28.0

**Comment by sastafford** [comment]
I set "enable_system_tables_schema_boolean" to TRUE.  

I received the following error for all the system schema work.  I don't have a good explanation for why there was not a metastore assigned to the current workspace.  I know that I upgraded the TF DBX provider from 1.50 to 1.51 and the issue was addressed.  

│ Error: cannot create system schema: No metastore assigned for the current workspace.
│ 
│   with module.SRA.module.public_preview_system_table[0].databricks_system_schema.storage,
│   on modules/sra/databricks_workspace/public_preview/system_schema/system_schema.tf line 23, in resource "databricks_system_schema" "storage":
│   23: resource "databricks_system_schema" "storage" {`

**Comment by JDBraun** [comment]
hmm, this might be a hidden race condition - can you try again with 1.50.0 from the start and do:

`module "system_table" {
  source = "./databricks_workspace/workspace_security_modules/system_schema/"
  count  = var.enable_system_tables_schema_boolean ? 1 : 0
  providers = {
    databricks = databricks.created_workspace
  }
  depends_on = [ module.uc_assignment ]
}`

**Comment by jdbraun-db** [comment]
closed with #94 
- https://github.com/databricks/terraform-databricks-sra/blob/7bfbcd8455d807eb2cdff220ad89b8bdd93d0d97/aws/tf/modules/sra/databricks_workspace.tf#L76
