### ISSUE TITLE
[AWS] Update catalog name to _ instead of -

### ISSUE THREAD

**Issue by JDBraun** [databricks/terraform-databricks-sra#98]
We need - for AWS resource, but for SQL - makes things inconvenient, so we should do a replace for the catalog name of _

**Comment by jdbraun-db** [comment]
closed with #94 
- https://github.com/databricks/terraform-databricks-sra/blob/7bfbcd8455d807eb2cdff220ad89b8bdd93d0d97/aws/tf/modules/sra/databricks_workspace/workspace_security_modules/uc_catalog/uc_catalog.tf#L142
